kind = "web"
previewPath = "/"
title = "Tasty Crousty"
version = "1.0.0"
id = "artifacts/tasty-crousty"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 23145

[services.development]
run = "pnpm --filter @workspace/tasty-crousty run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/tasty-crousty", "run", "build" ]
publicDir = "artifacts/tasty-crousty/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "23145"
BASE_PATH = "/"
